# Generated by Django 4.2.7 on 2024-11-22 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BotilleríaApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='botellas',
            name='cantidad',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
