# Generated by Django 4.2.7 on 2024-11-22 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BotilleríaApp', '0002_botellas_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='botellas',
            name='imagen',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
